### ISSUE TITLE
Mathkeyboard doesn't  work/throws error - Javascript error

### ISSUE THREAD

**Issue by UliPrantz** [DylanXie123/Num-Plus-Plus#2]
**Describe the bug**
When I press any button on the mathkeyboard nothing occurs on the display but following error is thrown: 

`JavaScript string was: 'addCmd('9', {isOperator: false})'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: addCmd, WKJavaScriptExceptionColumnNumber=7, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred}`

**To Reproduce**
Just start the App (in my case iPhone Simulator 11 Pro Max - iOS 13.3) and try to type any kind of Input with the mathkeyboard.

**Expected behavior**

Normally the keyboard expression should appear in the WebView.

**Version:**
 - iPhone Simulator 11 Pro Max - iOS 13.3

**Comment by DylanXie123** [comment]
I used some packages that require extra settings in iOS devices like `webview_flutter` and `flutter_tex`, but I don't have a mac device to test it. Maybe the following steps can help:
- adding a boolean property to the app's `Info.plist` file, with the key `io.flutter.embedded_views_preview` and the value` YES`.
- add following code in your `<project-directory>/ios/Runner/Info.plist`
```xml
<key>NSAppTransportSecurity</key>
  
  <dict>
    <key>NSAllowsArbitraryLoads</key> <true/>
  </dict>

<key>io.flutter.embedded_views_preview</key> <true/> 
```

**Comment by HardVeur** [comment]
Ok I will test it if you want to I can contribute more often in the future and make iOS support stable.

Thanks for the advice :)
